[package]
name = "sa"
<<<<<<< HEAD
version = "0.1.0"
edition = "2021"
=======
version = "0.0.7"
edition = "2024"
>>>>>>> 476881f6607f35272e054b7f324583281c0dff29

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.45", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["json", "stream"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
sha2 = "0.10.8"
hex = "0.4.3"
dirs = "5.0.1"
tar = "0.4.40"
flate2 = "1.0.28"
walkdir = "2.4.0"
csv = "1.3.0"
regex = "1.10.2"
uuid = { version = "1.6.1", features = ["v4"] }
base64 = "0.22.0"
petgraph = "0.6.4"
colored = "2.1.0"
indicatif = "0.17.7"
toml = "0.8.8"
semver = "1.0.20"
rusqlite = { version = "0.30.0", features = ["bundled"] }
bollard = "0.15.0"
futures-util = "0.3.29"
tempfile = "3.8.1"
